/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {},
  },
  corePlugins: {
    preflight: true,
    container: true,
    space: true,
    divideWidth: true,
    divideColor: true,
    divideStyle: true,
    divideOpacity: true,
    accessibility: true,
    appearance: true,
    backgroundAttachment: true,
    backgroundImage: true,
    gradientColorStops: true,
    backgroundOpacity: true,
    backgroundPosition: true,
    backgroundRepeat: true,
    backgroundSize: true,
    borderCollapse: true,
    borderColor: true,
    borderOpacity: true,
    borderRadius: true,
    borderStyle: true,
    borderWidth: true,
    boxSizing: true,
    cursor: true,
    fontFamily: true,
    fontWeight: true,
    objectFit: true,
    objectPosition: true,
    opacity: true,
    overscrollBehavior: true,
    placeholderColor: true,
    placeholderOpacity: true,
    pointerEvents: true,
    inset: true,
    resize: true,
    boxShadow: true,
    ringWidth: true,
    ringOffsetColor: true,
    ringOffsetWidth: true,
    ringColor: true,
    ringOpacity: true,
    fill: true,
    stroke: true,
    strokeWidth: true,
    textAlign: true,
    textColor: true,
    textOpacity: true,
    textOverflow: true,
    fontStyle: true,
    textTransform: true,
    textDecoration: true,
    fontSmoothing: true,
    fontVariantNumeric: true,
    letterSpacing: true,
    zIndex: true
  },
  plugins: [],
}